apiVersion: v1
kind: Secret
metadata:
  name: django-credentials
  labels:
    app: {{ template "django.name" . }}
    chart: {{ template "django.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | b64enc | quote }}
  apiUser: {{ .Values.env.apiUser | b64enc | quote }}
  apiPassword: {{ .Values.env.apiPassword | b64enc | quote }}

