apiVersion: v1
kind: Secret
metadata:
  name: django-credentials
  labels:
    app: {{ template "django.name" . }}
    chart: {{ template "django.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DJANGO_APP_DB_ENGINE: {{ .Values.env.DJANGO_APP_DB_ENGINE | b64enc | quote }}
  POSTGRES_DBNAME: {{ .Values.env.POSTGRES_DBNAME | b64enc | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | b64enc | quote }}