apiVersion: v1
kind: Secret
metadata:
  name: {{ template "django.fullname" . }}
  labels:
    app: {{ template "django.name" . }}
    chart: {{ template "django.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key,$value :=  .Values.env.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}